import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { Modal } from '@/shared/components/modals'

const montserrat = Montserrat({
  subsets: ['cyrillic'],
  variable: '--font-nunito',
  weight: ['400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ru' className={montserrat.variable}>
      <body className={montserrat.className}>
        {children}
        <Modal />
      </body>
    </html>
  )
}
